# 📌 Importação de bibliotecas

In [1]:
import numpy as np
import pandas as pd

In [2]:
from typing import Union

In [3]:
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant

In [5]:
from scipy.stats import f_oneway
from scipy.stats import levene
from scipy import stats
import pingouin as pg

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate, KFold
from sklearn.model_selection import StratifiedKFold
from imblearn.pipeline import Pipeline as imbpipeline
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import NearMiss
from yellowbrick.model_selection import FeatureImportances

from sklearn.dummy import DummyClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, mean_squared_log_error, mean_absolute_percentage_error
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import RocCurveDisplay
from sklearn.metrics import PrecisionRecallDisplay
from sklearn.metrics import average_precision_score
from sklearn.metrics import classification_report
from yellowbrick.classifier import ClassificationReport
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix,
    classification_report, roc_curve, auc, precision_recall_curve
)

In [7]:
import copy

In [8]:
import warnings

## Importação de pacotes locais

In [9]:
import src.local_tools as lt
import src.telecomx_analysis as ta
import src.telecomx_machine_learning as tml

## Configurações do ambiente

In [10]:
pd.set_option('display.max_columns', None)

In [11]:
warnings.simplefilter(action='ignore', category=FutureWarning)

## Constantes

In [12]:
NUM_SEMENTE_ALEATORIA = 42
TAMANHO_TESTE = 0.3
MAXIMO_ITERACAO = 1000

In [13]:
LIST_SCORING = ['accuracy','recall', 'precision', 'f1']

# 📌 Extração de dados

In [14]:
df_dados = pd.read_csv('./dados/dados_tratados.csv')

In [15]:
df_dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customerID                    7043 non-null   object
 1   Churn                         7043 non-null   int64
 2   customer_gender               7043 non-null   object
 3   customer_SeniorCitizen        7043 non-null   int64
 4   customer_Partner              7043 non-null   int64
 5   customer_Dependents           7043 non-null   int64
 6   customer_tenure               7043 non-null   int64
 7   phone_PhoneService            7043 non-null   int64
 8   phone_MultipleLines           7043 non-null   int64
 9   internet_InternetService      7043 non-null   int64
 10  internet_OnlineSecurity       7043 non-null   int64
 11  internet_OnlineBackup         7043 non-null   int64
 12  internet_DeviceProtection     7043 non-null   int64
 13  internet_TechSupport          7043 non-null   int64
 14  internet_StreamingTV          7043 non-null   int64
 15  internet_StreamingMovies      7043 non-null   int64
 16  account_Contract              7043 non-null   object
 17  account_PaperlessBilling      7043 non-null   int64
 18  account_PaymentMethod         7043 non-null   object
 19  account_Charges_Monthly       7043 non-null   float64
 20  account_Charges_Total         7043 non-null   float64
 21  internet_Service_Description  7043 non-null   object
 22  customer_tenure_bins          7043 non-null   object
 23  account_Charges_Monthly_bins  7043 non-null   object
 24  account_Charges_Total_bins    7043 non-null   object
 25  account_Contract_Monthly      7043 non-null   int64
 26  additional_InternetService    7043 non-null   int64
 27  only_PhoneService             7043 non-null   int64
 28  only_InternetService          7043 non-null   int64
 29  both_Phone_InternetService    7043 non-null   int64
 30  account_Charges_Daily         7043 non-null   float64
dtypes: float64(3), int64(20), object(8)
memory usage: 1.7+ MB

In [16]:
df_dados.nunique()

customerID                      7043
Churn                              2
customer_gender                    2
customer_SeniorCitizen             2
customer_Partner                   2
customer_Dependents                2
customer_tenure                   72
phone_PhoneService                 2
phone_MultipleLines                2
internet_InternetService           2
internet_OnlineSecurity            2
internet_OnlineBackup              2
internet_DeviceProtection          2
internet_TechSupport               2
internet_StreamingTV               2
internet_StreamingMovies           2
account_Contract                   3
account_PaperlessBilling           2
account_PaymentMethod              4
account_Charges_Monthly         1585
account_Charges_Total           6534
internet_Service_Description       3
customer_tenure_bins               6
account_Charges_Monthly_bins       6
account_Charges_Total_bins        13
account_Contract_Monthly           2
additional_InternetService         7
only_PhoneService                  2
only_InternetService               2
both_Phone_InternetService         2
account_Charges_Daily           1585
dtype: int64

Verificar dados duplicados

In [17]:
df_dados.duplicated().sum()

0

# 📌 Tratamento de dados

In [18]:
df_ohe = tml.df_final_modelo_v1(df_dados)

# 📌 Seleção e validação dos modelos de treinamento

## Tabela de verificação de padronização dos dados

| Modelo                 | Precisa padronizar? | Tipo de padronização (se necessário)   |
| ---------------------- | ------------------- | -------------------------------------- |
| DecisionTreeClassifier | ❌ Não               | —                                      |
| LogisticRegression     | ✅ Sim               | `StandardScaler` (média 0, desvio 1)   |
| RandomForest           | ❌ Não               | —                                      |
| XGBoost                | ⚠️ Opcional         | Pode ajudar (StandardScaler ou MinMax) |
| LightGBM               | ⚠️ Opcional         | Pode ajudar (StandardScaler ou MinMax) |
| CatBoost               | ❌ Não               | —                                      |

## Conceitos sobre as métricas de um modelo

Aqui está o quadro comparativo para churn (evasão de clientes), considerando que a classe positiva é “cliente vai sair”:

| **Métrica**                | **O que mede**                                                                     | **Quando valor é alto**                                        | **Risco quando valor é baixo**                                   | **Custo de erro associado**                                                |
| -------------------------- | ---------------------------------------------------------------------------------- | -------------------------------------------------------------- | ---------------------------------------------------------------- | -------------------------------------------------------------------------- |
| **Precisão (Precision)**   | Entre todos que o modelo previu como “vai sair”, qual porcentagem realmente saiu   | Você gasta retenção apenas em quem de fato sairia              | Gastar recursos em retenção de clientes que iam ficar (FP alto)  | **Custo financeiro** com campanhas desnecessárias (descontos, bônus, etc.) |
| **Recall (Sensibilidade)** | Entre todos que realmente saíram, qual porcentagem o modelo previu como “vai sair” | Você identifica a maior parte dos clientes que iam sair        | Deixar escapar clientes que saem (FN alto)                       | **Perda de receita** e potencial perda de market share                     |
| **F1-Score**               | Média harmônica de precisão e recall                                               | Equilíbrio entre acertar quem vai sair e evitar falsos alarmes | Ou alto custo de retenção inútil ou perda de clientes — ou ambos | **Equilíbrio financeiro e estratégico** — custo total menor                |
| **FP (Falso Positivo)**    | Previu saída, mas o cliente ficaria                                                | —                                                              | Gastar para reter quem não ia sair                               | Desperdício de budget de retenção                                          |
| **FN (Falso Negativo)**    | Previu permanência, mas o cliente saiu                                             | —                                                              | Não agir para reter quem realmente sairia                        | Perda direta de receita + possível impacto na reputação                    |

📌 Resumo visual da prioridade

    Se retenção for muito cara → priorizar alta precisão.

    Se perder clientes for muito prejudicial → priorizar alto recall.

    Se quer balancear ambos → otimizar F1-Score.

## Split base de dados em train e test

In [19]:
X = df_ohe.drop(columns=['Churn'])

In [20]:
y = df_ohe.Churn

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = NUM_SEMENTE_ALEATORIA, test_size=TAMANHO_TESTE, stratify=y)

## Treinamento do Modelo - CatBoost

In [22]:
from catboost import CatBoostClassifier

In [23]:
model_cbc = CatBoostClassifier(
    n_estimators=300,
    random_state=NUM_SEMENTE_ALEATORIA
)

In [24]:
model_cbc.fit(X_train, y_train)

Learning rate set to 0.061413
0:	learn: 0.6533179	total: 218ms	remaining: 1m 5s
1:	learn: 0.6216230	total: 225ms	remaining: 33.6s
2:	learn: 0.5942212	total: 231ms	remaining: 22.8s
3:	learn: 0.5687756	total: 236ms	remaining: 17.5s
4:	learn: 0.5483945	total: 244ms	remaining: 14.4s
5:	learn: 0.5304279	total: 250ms	remaining: 12.2s
6:	learn: 0.5166546	total: 256ms	remaining: 10.7s
7:	learn: 0.5039794	total: 261ms	remaining: 9.51s
8:	learn: 0.4937180	total: 265ms	remaining: 8.56s
9:	learn: 0.4859991	total: 269ms	remaining: 7.79s
10:	learn: 0.4772230	total: 274ms	remaining: 7.19s
11:	learn: 0.4700168	total: 278ms	remaining: 6.66s
12:	learn: 0.4646940	total: 281ms	remaining: 6.21s
13:	learn: 0.4589160	total: 286ms	remaining: 5.84s
14:	learn: 0.4547355	total: 290ms	remaining: 5.5s
15:	learn: 0.4499822	total: 293ms	remaining: 5.2s
16:	learn: 0.4476263	total: 297ms	remaining: 4.94s
17:	learn: 0.4446294	total: 300ms	remaining: 4.7s
18:	learn: 0.4420637	total: 305ms	remaining: 4.51s
19:	learn: 0.4404653	total: 308ms	remaining: 4.31s
20:	learn: 0.4397917	total: 310ms	remaining: 4.13s
21:	learn: 0.4375392	total: 314ms	remaining: 3.97s
22:	learn: 0.4346264	total: 318ms	remaining: 3.83s
23:	learn: 0.4330293	total: 322ms	remaining: 3.7s
24:	learn: 0.4308327	total: 325ms	remaining: 3.58s
25:	learn: 0.4285235	total: 329ms	remaining: 3.46s
26:	learn: 0.4267515	total: 332ms	remaining: 3.36s
27:	learn: 0.4251725	total: 336ms	remaining: 3.27s
28:	learn: 0.4239101	total: 340ms	remaining: 3.17s
29:	learn: 0.4226704	total: 343ms	remaining: 3.09s
30:	learn: 0.4215750	total: 347ms	remaining: 3.01s
31:	learn: 0.4205218	total: 351ms	remaining: 2.94s
32:	learn: 0.4194564	total: 355ms	remaining: 2.87s
33:	learn: 0.4186437	total: 358ms	remaining: 2.8s
34:	learn: 0.4179396	total: 362ms	remaining: 2.74s
35:	learn: 0.4168249	total: 366ms	remaining: 2.69s
36:	learn: 0.4155592	total: 370ms	remaining: 2.63s
37:	learn: 0.4144392	total: 375ms	remaining: 2.59s
38:	learn: 0.4137339	total: 380ms	remaining: 2.54s
39:	learn: 0.4128315	total: 385ms	remaining: 2.5s
40:	learn: 0.4123140	total: 389ms	remaining: 2.46s
41:	learn: 0.4118220	total: 392ms	remaining: 2.41s
42:	learn: 0.4109863	total: 397ms	remaining: 2.37s
43:	learn: 0.4102291	total: 401ms	remaining: 2.33s
44:	learn: 0.4097065	total: 405ms	remaining: 2.29s
45:	learn: 0.4090330	total: 409ms	remaining: 2.26s
46:	learn: 0.4084001	total: 415ms	remaining: 2.23s
47:	learn: 0.4082323	total: 419ms	remaining: 2.2s
48:	learn: 0.4076849	total: 424ms	remaining: 2.17s
49:	learn: 0.4070290	total: 430ms	remaining: 2.15s
50:	learn: 0.4063003	total: 435ms	remaining: 2.12s
51:	learn: 0.4057493	total: 440ms	remaining: 2.1s
52:	learn: 0.4049540	total: 448ms	remaining: 2.09s
53:	learn: 0.4045722	total: 452ms	remaining: 2.06s
54:	learn: 0.4039072	total: 456ms	remaining: 2.03s
55:	learn: 0.4035860	total: 460ms	remaining: 2.01s
56:	learn: 0.4031849	total: 464ms	remaining: 1.98s
57:	learn: 0.4029687	total: 467ms	remaining: 1.95s
58:	learn: 0.4024709	total: 471ms	remaining: 1.92s
59:	learn: 0.4018649	total: 474ms	remaining: 1.9s
60:	learn: 0.4015346	total: 479ms	remaining: 1.88s
61:	learn: 0.4010438	total: 482ms	remaining: 1.85s
62:	learn: 0.4008176	total: 486ms	remaining: 1.83s
63:	learn: 0.4002335	total: 489ms	remaining: 1.8s
64:	learn: 0.3998889	total: 494ms	remaining: 1.78s
65:	learn: 0.3995857	total: 497ms	remaining: 1.76s
66:	learn: 0.3990932	total: 501ms	remaining: 1.74s
67:	learn: 0.3988135	total: 504ms	remaining: 1.72s
68:	learn: 0.3985041	total: 508ms	remaining: 1.7s
69:	learn: 0.3984033	total: 511ms	remaining: 1.68s
70:	learn: 0.3979168	total: 515ms	remaining: 1.66s
71:	learn: 0.3975933	total: 518ms	remaining: 1.64s
72:	learn: 0.3969757	total: 522ms	remaining: 1.62s
73:	learn: 0.3963327	total: 526ms	remaining: 1.6s
74:	learn: 0.3961035	total: 529ms	remaining: 1.59s
75:	learn: 0.3959900	total: 532ms	remaining: 1.57s
76:	learn: 0.3957739	total: 536ms	remaining: 1.55s
77:	learn: 0.3951876	total: 540ms	remaining: 1.54s
78:	learn: 0.3948319	total: 544ms	remaining: 1.52s
79:	learn: 0.3943509	total: 547ms	remaining: 1.5s
80:	learn: 0.3940136	total: 551ms	remaining: 1.49s
81:	learn: 0.3935083	total: 555ms	remaining: 1.48s
82:	learn: 0.3934236	total: 558ms	remaining: 1.46s
83:	learn: 0.3930082	total: 561ms	remaining: 1.44s
84:	learn: 0.3925670	total: 565ms	remaining: 1.43s
85:	learn: 0.3919861	total: 568ms	remaining: 1.41s
86:	learn: 0.3915522	total: 573ms	remaining: 1.4s
87:	learn: 0.3911873	total: 577ms	remaining: 1.39s
88:	learn: 0.3911517	total: 579ms	remaining: 1.37s
89:	learn: 0.3907936	total: 583ms	remaining: 1.36s
90:	learn: 0.3903315	total: 586ms	remaining: 1.35s
91:	learn: 0.3901307	total: 590ms	remaining: 1.33s
92:	learn: 0.3899097	total: 593ms	remaining: 1.32s
93:	learn: 0.3896336	total: 597ms	remaining: 1.31s
94:	learn: 0.3892975	total: 600ms	remaining: 1.29s
95:	learn: 0.3891823	total: 606ms	remaining: 1.29s
96:	learn: 0.3887617	total: 610ms	remaining: 1.27s
97:	learn: 0.3885646	total: 613ms	remaining: 1.26s
98:	learn: 0.3882797	total: 617ms	remaining: 1.25s
99:	learn: 0.3881743	total: 620ms	remaining: 1.24s
100:	learn: 0.3878619	total: 624ms	remaining: 1.23s
101:	learn: 0.3876072	total: 627ms	remaining: 1.22s
102:	learn: 0.3872424	total: 631ms	remaining: 1.21s
103:	learn: 0.3870446	total: 635ms	remaining: 1.2s
104:	learn: 0.3867502	total: 639ms	remaining: 1.19s
105:	learn: 0.3865309	total: 642ms	remaining: 1.18s
106:	learn: 0.3862965	total: 646ms	remaining: 1.16s
107:	learn: 0.3860656	total: 650ms	remaining: 1.15s
108:	learn: 0.3860279	total: 652ms	remaining: 1.14s
109:	learn: 0.3857187	total: 656ms	remaining: 1.13s
110:	learn: 0.3854222	total: 659ms	remaining: 1.12s
111:	learn: 0.3850935	total: 662ms	remaining: 1.11s
112:	learn: 0.3846668	total: 667ms	remaining: 1.1s
113:	learn: 0.3842740	total: 670ms	remaining: 1.09s
114:	learn: 0.3841274	total: 674ms	remaining: 1.08s
115:	learn: 0.3838220	total: 677ms	remaining: 1.07s
116:	learn: 0.3836021	total: 681ms	remaining: 1.06s
117:	learn: 0.3833789	total: 685ms	remaining: 1.05s
118:	learn: 0.3832473	total: 688ms	remaining: 1.05s
119:	learn: 0.3828450	total: 691ms	remaining: 1.04s
120:	learn: 0.3826831	total: 695ms	remaining: 1.03s
121:	learn: 0.3824664	total: 699ms	remaining: 1.02s
122:	learn: 0.3822658	total: 703ms	remaining: 1.01s
123:	learn: 0.3820357	total: 706ms	remaining: 1s
124:	learn: 0.3816296	total: 710ms	remaining: 994ms
125:	learn: 0.3812701	total: 714ms	remaining: 986ms
126:	learn: 0.3812408	total: 716ms	remaining: 976ms
127:	learn: 0.3809169	total: 720ms	remaining: 967ms
128:	learn: 0.3805741	total: 723ms	remaining: 959ms
129:	learn: 0.3802856	total: 727ms	remaining: 950ms
130:	learn: 0.3799622	total: 731ms	remaining: 943ms
131:	learn: 0.3796462	total: 734ms	remaining: 935ms
132:	learn: 0.3794487	total: 738ms	remaining: 926ms
133:	learn: 0.3790790	total: 741ms	remaining: 918ms
134:	learn: 0.3787853	total: 746ms	remaining: 911ms
135:	learn: 0.3785741	total: 749ms	remaining: 903ms
136:	learn: 0.3785183	total: 752ms	remaining: 895ms
137:	learn: 0.3782290	total: 756ms	remaining: 887ms
138:	learn: 0.3779303	total: 759ms	remaining: 879ms
139:	learn: 0.3776728	total: 763ms	remaining: 872ms
140:	learn: 0.3773154	total: 767ms	remaining: 865ms
141:	learn: 0.3771156	total: 770ms	remaining: 857ms
142:	learn: 0.3766583	total: 774ms	remaining: 850ms
143:	learn: 0.3761358	total: 778ms	remaining: 843ms
144:	learn: 0.3759045	total: 782ms	remaining: 836ms
145:	learn: 0.3755946	total: 785ms	remaining: 828ms
146:	learn: 0.3752344	total: 789ms	remaining: 821ms
147:	learn: 0.3748848	total: 792ms	remaining: 814ms
148:	learn: 0.3745886	total: 796ms	remaining: 807ms
149:	learn: 0.3744708	total: 799ms	remaining: 799ms
150:	learn: 0.3741045	total: 803ms	remaining: 792ms
151:	learn: 0.3740813	total: 805ms	remaining: 784ms
152:	learn: 0.3740432	total: 808ms	remaining: 776ms
153:	learn: 0.3737775	total: 812ms	remaining: 769ms
154:	learn: 0.3732164	total: 815ms	remaining: 762ms
155:	learn: 0.3729594	total: 818ms	remaining: 755ms
156:	learn: 0.3726233	total: 822ms	remaining: 749ms
157:	learn: 0.3720441	total: 826ms	remaining: 743ms
158:	learn: 0.3717306	total: 830ms	remaining: 736ms
159:	learn: 0.3711989	total: 833ms	remaining: 729ms
160:	learn: 0.3708336	total: 837ms	remaining: 722ms
161:	learn: 0.3705159	total: 841ms	remaining: 716ms
162:	learn: 0.3702482	total: 845ms	remaining: 710ms
163:	learn: 0.3700024	total: 848ms	remaining: 703ms
164:	learn: 0.3697075	total: 852ms	remaining: 697ms
165:	learn: 0.3694806	total: 856ms	remaining: 691ms
166:	learn: 0.3692265	total: 859ms	remaining: 684ms
167:	learn: 0.3689248	total: 863ms	remaining: 678ms
168:	learn: 0.3684091	total: 866ms	remaining: 671ms
169:	learn: 0.3681447	total: 870ms	remaining: 665ms
170:	learn: 0.3680336	total: 874ms	remaining: 660ms
171:	learn: 0.3677645	total: 878ms	remaining: 653ms
172:	learn: 0.3676132	total: 881ms	remaining: 647ms
173:	learn: 0.3673784	total: 885ms	remaining: 641ms
174:	learn: 0.3671329	total: 889ms	remaining: 635ms
175:	learn: 0.3669320	total: 894ms	remaining: 630ms
176:	learn: 0.3665031	total: 898ms	remaining: 624ms
177:	learn: 0.3661341	total: 902ms	remaining: 618ms
178:	learn: 0.3656959	total: 909ms	remaining: 614ms
179:	learn: 0.3653663	total: 916ms	remaining: 610ms
180:	learn: 0.3651665	total: 922ms	remaining: 606ms
181:	learn: 0.3647800	total: 929ms	remaining: 602ms
182:	learn: 0.3646226	total: 937ms	remaining: 599ms
183:	learn: 0.3643885	total: 940ms	remaining: 593ms
184:	learn: 0.3640997	total: 944ms	remaining: 587ms
185:	learn: 0.3639248	total: 947ms	remaining: 581ms
186:	learn: 0.3633731	total: 952ms	remaining: 575ms
187:	learn: 0.3631218	total: 956ms	remaining: 569ms
188:	learn: 0.3628601	total: 959ms	remaining: 563ms
189:	learn: 0.3626518	total: 963ms	remaining: 557ms
190:	learn: 0.3624524	total: 967ms	remaining: 552ms
191:	learn: 0.3621799	total: 971ms	remaining: 546ms
192:	learn: 0.3618885	total: 974ms	remaining: 540ms
193:	learn: 0.3617372	total: 978ms	remaining: 534ms
194:	learn: 0.3615010	total: 982ms	remaining: 529ms
195:	learn: 0.3613654	total: 985ms	remaining: 523ms
196:	learn: 0.3612111	total: 989ms	remaining: 517ms
197:	learn: 0.3610325	total: 992ms	remaining: 511ms
198:	learn: 0.3607742	total: 996ms	remaining: 506ms
199:	learn: 0.3606043	total: 1s	remaining: 500ms
200:	learn: 0.3604865	total: 1s	remaining: 495ms
201:	learn: 0.3602936	total: 1.01s	remaining: 489ms
202:	learn: 0.3601606	total: 1.01s	remaining: 484ms
203:	learn: 0.3599292	total: 1.02s	remaining: 479ms
204:	learn: 0.3596457	total: 1.02s	remaining: 473ms
205:	learn: 0.3594121	total: 1.02s	remaining: 468ms
206:	learn: 0.3590931	total: 1.03s	remaining: 462ms
207:	learn: 0.3586220	total: 1.03s	remaining: 457ms
208:	learn: 0.3582575	total: 1.04s	remaining: 452ms
209:	learn: 0.3579145	total: 1.04s	remaining: 446ms
210:	learn: 0.3577792	total: 1.04s	remaining: 441ms
211:	learn: 0.3575345	total: 1.05s	remaining: 435ms
212:	learn: 0.3572928	total: 1.05s	remaining: 430ms
213:	learn: 0.3570620	total: 1.06s	remaining: 425ms
214:	learn: 0.3569485	total: 1.06s	remaining: 420ms
215:	learn: 0.3566403	total: 1.06s	remaining: 414ms
216:	learn: 0.3564259	total: 1.07s	remaining: 409ms
217:	learn: 0.3561084	total: 1.07s	remaining: 403ms
218:	learn: 0.3558878	total: 1.08s	remaining: 398ms
219:	learn: 0.3556473	total: 1.08s	remaining: 393ms
220:	learn: 0.3554449	total: 1.08s	remaining: 388ms
221:	learn: 0.3552074	total: 1.09s	remaining: 382ms
222:	learn: 0.3550221	total: 1.09s	remaining: 377ms
223:	learn: 0.3548564	total: 1.09s	remaining: 372ms
224:	learn: 0.3546628	total: 1.1s	remaining: 366ms
225:	learn: 0.3544618	total: 1.1s	remaining: 361ms
226:	learn: 0.3543928	total: 1.1s	remaining: 356ms
227:	learn: 0.3542852	total: 1.11s	remaining: 350ms
228:	learn: 0.3541410	total: 1.11s	remaining: 345ms
229:	learn: 0.3538802	total: 1.12s	remaining: 340ms
230:	learn: 0.3536696	total: 1.12s	remaining: 334ms
231:	learn: 0.3533842	total: 1.12s	remaining: 330ms
232:	learn: 0.3532905	total: 1.13s	remaining: 324ms
233:	learn: 0.3530507	total: 1.13s	remaining: 319ms
234:	learn: 0.3528438	total: 1.13s	remaining: 314ms
235:	learn: 0.3527175	total: 1.14s	remaining: 309ms
236:	learn: 0.3525171	total: 1.14s	remaining: 304ms
237:	learn: 0.3524073	total: 1.15s	remaining: 298ms
238:	learn: 0.3522090	total: 1.15s	remaining: 293ms
239:	learn: 0.3520380	total: 1.15s	remaining: 288ms
240:	learn: 0.3517988	total: 1.16s	remaining: 283ms
241:	learn: 0.3514153	total: 1.16s	remaining: 278ms
242:	learn: 0.3513006	total: 1.16s	remaining: 273ms
243:	learn: 0.3511244	total: 1.17s	remaining: 268ms
244:	learn: 0.3507835	total: 1.17s	remaining: 263ms
245:	learn: 0.3505594	total: 1.18s	remaining: 258ms
246:	learn: 0.3504071	total: 1.18s	remaining: 253ms
247:	learn: 0.3500371	total: 1.18s	remaining: 248ms
248:	learn: 0.3498065	total: 1.19s	remaining: 243ms
249:	learn: 0.3497367	total: 1.19s	remaining: 238ms
250:	learn: 0.3495932	total: 1.19s	remaining: 233ms
251:	learn: 0.3495198	total: 1.2s	remaining: 228ms
252:	learn: 0.3493482	total: 1.2s	remaining: 223ms
253:	learn: 0.3491776	total: 1.2s	remaining: 218ms
254:	learn: 0.3490084	total: 1.21s	remaining: 213ms
255:	learn: 0.3488953	total: 1.21s	remaining: 208ms
256:	learn: 0.3486865	total: 1.21s	remaining: 203ms
257:	learn: 0.3485605	total: 1.22s	remaining: 199ms
258:	learn: 0.3483307	total: 1.22s	remaining: 194ms
259:	learn: 0.3481314	total: 1.23s	remaining: 189ms
260:	learn: 0.3480377	total: 1.23s	remaining: 184ms
261:	learn: 0.3477346	total: 1.23s	remaining: 179ms
262:	learn: 0.3474919	total: 1.24s	remaining: 174ms
263:	learn: 0.3473363	total: 1.24s	remaining: 169ms
264:	learn: 0.3471946	total: 1.24s	remaining: 164ms
265:	learn: 0.3468968	total: 1.25s	remaining: 160ms
266:	learn: 0.3467654	total: 1.25s	remaining: 155ms
267:	learn: 0.3465985	total: 1.25s	remaining: 150ms
268:	learn: 0.3462586	total: 1.26s	remaining: 145ms
269:	learn: 0.3460857	total: 1.26s	remaining: 140ms
270:	learn: 0.3459106	total: 1.27s	remaining: 136ms
271:	learn: 0.3457516	total: 1.27s	remaining: 131ms
272:	learn: 0.3455728	total: 1.27s	remaining: 126ms
273:	learn: 0.3453482	total: 1.28s	remaining: 121ms
274:	learn: 0.3452587	total: 1.28s	remaining: 117ms
275:	learn: 0.3450722	total: 1.28s	remaining: 112ms
276:	learn: 0.3449026	total: 1.29s	remaining: 107ms
277:	learn: 0.3447204	total: 1.29s	remaining: 102ms
278:	learn: 0.3445177	total: 1.3s	remaining: 97.6ms
279:	learn: 0.3442411	total: 1.3s	remaining: 92.9ms
280:	learn: 0.3441275	total: 1.3s	remaining: 88.1ms
281:	learn: 0.3440326	total: 1.31s	remaining: 83.4ms
282:	learn: 0.3438550	total: 1.31s	remaining: 78.7ms
283:	learn: 0.3437672	total: 1.31s	remaining: 74.1ms
284:	learn: 0.3436285	total: 1.32s	remaining: 69.4ms
285:	learn: 0.3434639	total: 1.32s	remaining: 64.7ms
286:	learn: 0.3432915	total: 1.32s	remaining: 60ms
287:	learn: 0.3431497	total: 1.33s	remaining: 55.4ms
288:	learn: 0.3429621	total: 1.33s	remaining: 50.7ms
289:	learn: 0.3427771	total: 1.33s	remaining: 46.1ms
290:	learn: 0.3425279	total: 1.34s	remaining: 41.4ms
291:	learn: 0.3423879	total: 1.34s	remaining: 36.8ms
292:	learn: 0.3422648	total: 1.35s	remaining: 32.2ms
293:	learn: 0.3421554	total: 1.35s	remaining: 27.6ms
294:	learn: 0.3419880	total: 1.35s	remaining: 23ms
295:	learn: 0.3418722	total: 1.36s	remaining: 18.3ms
296:	learn: 0.3416707	total: 1.36s	remaining: 13.8ms
297:	learn: 0.3415045	total: 1.37s	remaining: 9.17ms
298:	learn: 0.3414277	total: 1.37s	remaining: 4.58ms
299:	learn: 0.3412498	total: 1.37s	remaining: 0us

In [25]:
# 8️⃣ Fazer previsões
y_pred_cbc = model_cbc.predict(X_test)
y_pred_proba_cbc = model_cbc.predict(X_test)

### Relatório de métricas

In [26]:
tml.avaliar_modelo(y_test, y_pred_cbc, y_pred_proba_cbc, False)

Métricas:
Acurácia: 0.7837
Precisão: 0.6150
Recall: 0.4955
F1-Score: 0.5489
ROC AUC: 0.6917

Relatório de classificação:

              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1552
           1       0.62      0.50      0.55       561

    accuracy                           0.78      2113
   macro avg       0.72      0.69      0.70      2113
weighted avg       0.77      0.78      0.78      2113


Matrix de confusão:

[[1378  174]
 [ 283  278]]

In [27]:
tml.df_classifier_metrics(y_test, y_pred_cbc, y_pred_proba_cbc, ['CatBoost'])

,accuracy,precision,recall,f1,roc_auc,support,True Negative,False Positive,False Negative,True Positive
CatBoost,0.78372,0.615044,0.495544,0.548865,0.691715,2113,1378,174,283,278

In [28]:
list_df = []
colunas_binarias = lt.identify_columns_binary_values(X_test)
for c in colunas_binarias:
    list_df.append(tml.df_specific_confusion_matrix(X_test, y_test, y_pred_proba_cbc, c))
df_independent = pd.concat(list_df, axis=0)

E:\Local_Drive\Cursos Livres\ONE\06-Estatística e Machine Learning G8 - ONE\08-Challenge Telecom X - análise de evasão de clientes - Parte 2\TelecomX_parte2_BR\scripts\telecomx_machine_learning.py:251: RuntimeWarning: invalid value encountered in scalar divide
  precision = tp / (tp + fp)
E:\Local_Drive\Cursos Livres\ONE\06-Estatística e Machine Learning G8 - ONE\08-Challenge Telecom X - análise de evasão de clientes - Parte 2\TelecomX_parte2_BR\scripts\telecomx_machine_learning.py:253: RuntimeWarning: invalid value encountered in scalar divide
  f1_score = (2 * precision * recall) / (precision + recall)

In [29]:
df_independent.reset_index()

,index,filter_value,support,accuracy,negative predictive value,precision,recall,f1-score,TN,FP,FN,TP
0,customer_SeniorCitizen,1,349,0.727794,0.776650,0.664474,0.696552,0.680135,153,51,44,101
1,customer_Partner,1,1032,0.814922,0.855395,0.541353,0.356436,0.429851,769,61,130,72
2,customer_Dependents,1,616,0.840909,0.875220,0.425532,0.219780,0.289855,498,27,71,20
3,phone_MultipleLines,1,883,0.779162,0.830247,0.638298,0.576923,0.606061,538,85,110,150
4,account_PaperlessBilling,1,1213,0.752679,0.806258,0.636126,0.601485,0.618321,670,139,161,243
5,account_Contract_Monthly,1,1182,0.670897,0.705479,0.615044,0.563895,0.588360,515,174,215,278
6,additional_InternetService_0,1,676,0.838757,0.871750,0.646465,0.463768,0.540084,503,35,74,64
7,additional_InternetService_1,1,297,0.626263,0.666667,0.585034,0.632353,0.607774,100,61,50,86
8,additional_InternetService_2,1,291,0.701031,0.738693,0.619565,0.522936,0.567164,147,35,52,57
9,additional_InternetService_3,1,318,0.786164,0.810277,0.692308,0.483871,0.569620,205,20,48,45
10,additional_InternetService_4,1,281,0.822064,0.877119,0.533333,0.452830,0.489796,207,21,29,24
11,additional_InternetService_5,1,165,0.836364,0.844720,0.500000,0.074074,0.129032,136,2,25,2
12,additional_InternetService_6,1,85,0.941176,0.941176,NaN,0.000000,NaN,80,0,5,0
13,internet_Service_Description_DSL,1,753,0.804781,0.847534,0.464286,0.276596,0.346667,567,45,102,39
14,internet_Service_Description_Fiber_optic,1,897,0.692308,0.719397,0.653005,0.615979,0.633952,382,127,149,239
15,charges_total_bin__inf_96_62_,1,242,0.669421,0.664000,0.675214,0.652893,0.663866,83,38,42,79
16,charges_total_bin__1182_80_3273_68_,1,564,0.776596,0.829374,0.534653,0.406015,0.461538,384,47,79,54
17,charges_total_bin__198_05_347_90_,1,144,0.763889,0.801980,0.674419,0.591837,0.630435,81,14,20,29
18,charges_total_bin__3273_68_4838_38_,1,214,0.864486,0.897959,0.500000,0.310345,0.382979,176,9,20,9
19,charges_total_bin__347_90_547_73_,1,165,0.806061,0.868852,0.627907,0.627907,0.627907,106,16,16,27
20,charges_total_bin__4838_38_5644_60_,1,119,0.789916,0.805310,0.500000,0.120000,0.193548,91,3,22,3
21,charges_total_bin__547_73_1182_80_,1,309,0.809061,0.848739,0.676056,0.571429,0.619355,202,23,36,48
22,charges_total_bin__5644_60_6623_50_,1,131,0.824427,0.837209,0.000000,0.000000,NaN,108,2,21,0
23,charges_total_bin__6623_50_inf_,1,114,0.894737,0.893805,1.000000,0.076923,0.142857,101,0,12,1
24,charges_total_bin__96_62_198_05_,1,111,0.666667,0.754098,0.560000,0.651163,0.602151,46,22,15,28
25,account_PaymentMethod_automatic,1,891,0.851852,0.872263,0.608696,0.285714,0.388889,717,27,105,42
26,account_PaymentMethod_check,1,1222,0.734043,0.787843,0.616188,0.570048,0.592221,661,147,178,236

### Otimizando os hiperparâmetros com o GridSearchCV

param_grid = {
    'depth': [5, 10, 15],               # profundidade da árvore
    'learning_rate': [0.01, 0.1, 0.2],  # taxa de aprendizado
    'iterations': [100, 300, 500],      # número de árvores
    'min_data_in_leaf': [10, 20, 50],   # mínimo de amostras por folha
    'subsample': [0.6, 0.8, 1.0],       # fração de amostras
    'rsm': [0.6, 0.8, 1.0],             # fração de features
    'l2_leaf_reg': [1, 3, 5, 7],        # regularização L2
}

In [30]:
param_grid = {
    'depth': [5, 10],               # profundidade da árvore
    'learning_rate': [0.01, 0.1, 0.2],  # taxa de aprendizado
    'iterations': [100, 300],      # número de árvores
    'min_data_in_leaf': [10, 20],   # mínimo de amostras por folha
    'subsample': [0.6, 1.0],       # fração de amostras
    'rsm': [0.6, 1.0],             # fração de features
    'l2_leaf_reg': [3, 7],        # regularização L2
}

In [31]:
%%timeit
model_cbc = CatBoostClassifier(
    random_state=NUM_SEMENTE_ALEATORIA,
    verbose=0
)

25.9 µs ± 1.13 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [34]:
model_cbc = CatBoostClassifier(
    random_state=NUM_SEMENTE_ALEATORIA,
    verbose=0
)

In [35]:
model_grid_cbc = GridSearchCV(
    estimator=model_cbc,
    param_grid=param_grid,
    scoring='recall',
    cv=5,
    n_jobs=-1,
    verbose=1
)

In [36]:
model_grid_cbc.fit(X_train, y_train)

Fitting 5 folds for each of 192 candidates, totalling 960 fits

GridSearchCV(cv=5,
             estimator=<catboost.core.CatBoostClassifier object at 0x000002455BF07D50>,
             n_jobs=-1,
             param_grid={'depth': [5, 10], 'iterations': [100, 300],
                         'l2_leaf_reg': [3, 7],
                         'learning_rate': [0.01, 0.1, 0.2],
                         'min_data_in_leaf': [10, 20], 'rsm': [0.6, 1.0],
                         'subsample': [0.6, 1.0]},
             scoring='recall', verbose=1)

In [37]:
model_grid_cbc.best_params_

{'depth': 5,
 'iterations': 100,
 'l2_leaf_reg': 7,
 'learning_rate': 0.2,
 'min_data_in_leaf': 10,
 'rsm': 1.0,
 'subsample': 1.0}

In [38]:
y_pred_grid_cdc = model_grid_cbc.predict(X_test)

In [40]:
y_pred_proba_grid_cdc = model_grid_cbc.predict_proba(X_test)

In [41]:
tml.df_classifier_metrics(y_test, y_pred_grid_cdc, y_pred_proba_grid_cdc, ['CatBoost - Grid'])

,accuracy,precision,recall,f1,roc_auc,support,True Negative,False Positive,False Negative,True Positive
CatBoost - Grid,0.791765,0.632385,0.515152,0.56778,0.823744,2113,1384,168,272,289

### Consolidação das métricas

In [44]:
df_metricas = []

df_metricas.append(tml.df_classifier_metrics(y_test, y_pred_cbc, y_pred_proba_cbc, ['CatBoost']))

df_metricas.append(tml.df_classifier_metrics(y_test, y_pred_grid_cdc, y_pred_proba_grid_cdc, ['CatBoost - Grid']))

df_metricas = pd.concat(df_metricas, axis=0)
df_metricas

,accuracy,precision,recall,f1,roc_auc,support,True Negative,False Positive,False Negative,True Positive
CatBoost,0.783720,0.615044,0.495544,0.548865,0.691715,2113,1378,174,283,278
CatBoost - Grid,0.791765,0.632385,0.515152,0.567780,0.823744,2113,1384,168,272,289

In [38]:
df_metricas.to_clipboard()